#!/usr/bin/env bash

search_google() {
    query="$(echo "$*" | sed 's/\ /\+/g')"
    url="http://www.google.com/search?client=safari&rls=en&q=${query}&ie=UTF-8&oe=UTF-8"
    open -b com.apple.Safari "$url"
}

main() {
    search_google
}

main "$@"
